image: Visual Studio 2017

before_build:
    - ps: nuget restore

build:
    project: SpaghettiGenerator.sln

after_build:
    - ps: $ndproj = Resolve-Path .\SpaghettiGenerator.ndproj
    - ps: .\NDepend\NDepend.Console.exe $ndproj
